# Generated by Django 6.0.3 on 2026-03-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled Task', max_length=200),
            preserve_default=False,
        ),
    ]
